"""Add saralry column

Revision ID: 23363d807147
Revises: 83e75bf70906
Create Date: 2023-11-03 06:42:03.836161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23363d807147'
down_revision: Union[str, None] = '83e75bf70906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('job posts', sa.Column('saralry', sa.Integer(), default=10000))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
