"""Rename saralry column to salary

Revision ID: 8d0e8656e5cf
Revises: 23363d807147
Create Date: 2023-11-03 06:49:53.061071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0e8656e5cf'
down_revision: Union[str, None] = '23363d807147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column('job posts', 'saralry', new_column_name='salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
